### ISSUE TITLE
Rename RailsKaigi

### ISSUE THREAD

**Issue by yhirano55** [railsdm/meetup#11]
- 国際会議ではないからNG?
- スタンダードを占有すれば、良い試合運びができる?（登壇依頼は現在以上にしやすそう）
- Road to Rails Conf Tokyo?
- ruby-no-kaiに確認する?

https://github.com/ruby-no-kai/official/wiki/Regionalrubykaigi

**Comment by yuemori** [comment]
RailsKaigiを使えたらすごく大きいですね 👍  👍  👍 
Ginza RubyKaigiとか国際会議じゃなくても結構あるのでそこは大丈夫そうな印象です。

[IMO] ◯◯Kaigiは大きめの長時間イベントのイメージがある（1年に1回とか、◯周年記念とか）んで、とっておいてもよいかも？

**Comment by 284km** [comment]
> （登壇依頼は現在以上にしやすそう）

こういうのはありそうですね。railsdm を知らない方向けの説明は単純に楽になりそう。

**Comment by yhirano55** [comment]
1周年にとっておきましょうか。なんとなくのイメージですが、半年に1回、100-200名くらいの半日Meetup + 宴ができるといいのかも。

**Comment by yhirano55** [comment]
年1回と思っていたが、下記の命名ルールで調整できないか検討したい。

| Naming | Content |
|:---|:---|
| `RailsKaigi #1` | 末尾がナンバリング（月開催を表す） |
| `RailsKaigi 2017` | 末尾が西暦（年1開催を表す） |

年1回のイベントについては、RubyKaigiと同規模であること、国際会議であること、などを要件に盛り込むと、開催自体が困難になるので、要求ハードルをあげすぎずに「小さく始める」のが妥当と感じた。そのため、下記は労力を惜しまない人が集まったら、そのとき実現できれば尚良い、くらいの認識で始めるのがよいと思う。

- 海外からゲストを招待すること
- 国際会議場で行うこと
- ドリンクアップなどを同規模で行うこと
- 英語のセッションであること（通訳を呼ぶこと）

見栄や体裁のためにテックカンファレンスを行うわけではなく、本質は技術促進・学習・普及などのためにあるので、たちあがりはベストエフォートな実現でよい気がする。最初は小さく始めて、松田さんにアドバイザーとなっていただき、適宜ご意見をいただきながら、徐々に発展させていく方向がよさそう。

ちなみに月次開催の方は、リネームのみ行う方向でよい気がした。とりあえず、 `railskaigi.org` ドメインを自費で購入した。

**Comment by 284km** [comment]
よさそう！
一応思いつく案だけ出しておくと、毎回（毎月）開催されるのは Rails Developers Meetup という名前のままで、 年一回の方だけ RailsKaigi 2017 などの名称を使う。というパターン。
この場合は RailsKaigi の特別感？が高まると思う（うまく説明できていない...）。毎月同じ名前で催されていると年一回の物もいつもの延長みたいになって、なんか薄まる？可能性はあるかもなーと。
どちらが良いのか今のところ判断がついていません。
小さく始める、ベストエフォートは同意ですね:+1:

**Comment by yhirano55** [comment]
特別感を出すことで期待値を上げてしまうと、特別なことをやらなければならなくなるので、実現が遠のく可能性があるかな。なので、毎月開催もRailsKaigiって名前がいいかなと思います。

地域.rbと地域RubyKaigiと、同じ規則性になくていいんじゃないかなと思うのと、Rails Developers Meetupは、現状で、毎月、地域.rb以上の規模感でやっているので。

**Comment by yhirano55** [comment]
いずれにせよ、RubyKaigiの概念に引っ張られる必要はなく、自分たちができる規模やスタイルでやればいいと思うんですよね。誰かに求められて実施するわけではなく、単なる自主企画だしね。

**Comment by 284km** [comment]
たしかに。大事なことですね。この先もここの判断だけは間違うことの無いようにしたい。
これは RubyKaigi の歴史からも学べることなのでしょうね。(卜部さんの記事とか思い出しつつ)
