### ISSUE TITLE
Rails Developers Meetup 2017: 登壇テーマ 入稿窓口

### ISSUE THREAD

**Issue by yhirano55** [railsdm/meetup#15]
この度は、Rails Developers Meetup 2017のご登壇をお引き受けいただき、
誠にありがとうございます。

募集ページに登壇テーマを掲載するため、ご協力のほどお願いいたします。

### 登壇テーマ

Railsだけでなく、Ruby・フロントエンド・コンテナ技術・パフォーマンス・セキュリティ・アンチパターン・技術的負債・データベース・OSS開発・レビュー・ワークフロー・マネジメント・教育・採用戦略・コミュニティなど、何でも歓迎いたします。ニッチな内容でも構いません。実務で得られた知見を共有いただけると幸いです。

### フォーマット

* タイトル
* 説明文（80〜200文字程度）

過去のイベント募集ページの[タイムスケジュール](https://techplay.jp/event/631406)より、雰囲気をご確認いただけると幸いです。

### スケジュール

- 入稿期限: 2017/11/3（金）
- 掲載開始: 2017/11/6（月）12:00から

### 入稿方法

こちらのIssueのコメントフォームよりご投稿ください。

現時点で決めるのは難しいと思いますので、 __いくつか思いつく仮タイトル・説明文をWIPで作成していただき、締め切り前に決めていただく方向__ でも問題ありません。

### テーマの重複について

**運営側としては、（トークの背景にある個々の経験が異なるため）登壇内容の重複は問いません**が、もしも気になるようでしたら、本Issueのログをご確認いただき、ご検討いただけると幸いです。

### 所属企業のご紹介について

冒頭や最後にメッセージを発信することは問題ございません。
（We're hiring! なメッセージも特に規定はございません）

### 質問について

何か気になることがあれば、こちらのIssueか、 [@yoshi_hirano](https://twitter.com/yoshi_hirano) 宛にお気軽にDMを送ってください。

**Comment by willnet** [comment]
とりあえずWIPで出しておきます(\( ⁰⊖⁰)/)

# レールの伸ばし方

Railsを使ってwebサービスを開発する際、最初は実装がどんどん進んで最高な気分ですが、だんだんと負債が溜まっていきつらみが高まる経験を皆さんされていると思います。Railsが提供するデフォルトのレイヤーをそのまま使うだけでは大抵の場合行き詰まることになるでしょう。この発表ではRailsの提供していないレイヤーをうまく追加して、大きめのアプリケーションをきれいに作るためのコツについて共有します。

**Comment by yhirano55** [comment]
WIPありがとうございます！
レイヤー追加する勢・しない勢がいるので、とても興味深い内容...！！

**Comment by toshimaru** [comment]
## 「Railsでまだ消耗しているの？」 ー僕らがRailsで戦い続けるワケー

なぜRailsを採用するのかーーあなたならこの問いにどう答えるでしょうか。Railsは遅い、RailsのRailには乗りたくない、Ruby/Railsの黒魔術が怖い…さまざまな批判の声も聞こえてきます。本発表ではなぜ今Railsなのか、”Why Ruby?” “Why Rails?” という２つの観点から考えたいと思います。

**Comment by JunichiIto** [comment]
某所で話そうと思っていたけどお蔵入りになってしまったネタを復活させようかなーと考えています。  

## ActiveRecordの向き不向きを理解し、生SQLを活用しよう

Railsを使うなら生SQLを書きたくない？いやいや、ActiveRecordにも向き不向きはあります。ActiveRecordに向いていない処理はさくっと生SQLで書いちゃいましょう。この講演ではActiveRecordの向き不向きを見分けるポイントや、Railsアプリ内で生SQLを活用するためのテクニックを紹介します。

**Comment by yuemori** [comment]
まだ内容がしっかりまとまってないのでWIPです。
後者は少しコア過ぎる気もするので考え中ですが、どちらにするか決まったら改めて。

## MicroserviceにおけるAPIサーバのテスト、型との戦い

MicroserviceのAPIサーバとしてRailsを採用する場合、型との戦いは避けられません。JSON/MessagePack/Protocol Bufferなど様々なシリアライズフォーマットがありますが、いずれも型が存在するためです。型のないRubyでどうやってそれらとどう戦うのか、ツールや戦略について考察・紹介します。
また、request specを書くときのポイントについても話します。

## MMORPGのアーキテクチャ、APIサーバ、Rails

古くから存在するゲームのジャンルであるMMORPGですが、そのアーキテクチャについてはご存知でしょうか？　MMORPGの一般的なアーキテクチャとその進化、APIサーバの役割、そしてそれらをRailsでどうやって開発していくかについて話します。

**Comment by k0kubun** [comment]
## React時代のRailsアプリケーションアーキテクチャ
Railsでシンプルなページを作る場合、テンプレートエンジンやRailsのヘルパーを活用することで高速にWebアプリケーションを開発することができます。一方、最近ではReactなどのフレームワークを使ってリッチなフロントエンドを開発することが増えてきており、従来とは違ったRailsアプリの開発方法を取る必要が出てきています。この発表では、フロントエンドの実装がRailsに同居しているパターン、そうでないパターンの両方の開発経験から、それぞれの手法におけるベストプラクティスや、どちらがどういう要件に向いているかについて議論します。

<hr>

同居しているパターンはwebpackerについて触れるので、willnetさんと微妙に内容が被る予感がしていますが、もしそうでもそれぞれの微妙な違いが見れると面白いと思うのでそのまま行こうと思います

**Comment by willnet** [comment]
@k0kubun 僕のはサービスオブジェクトとかフォームオブジェクトとかDCIとか、サーバサイドメインな話の予定なので被らないかと思いますー

**Comment by k0kubun** [comment]
承知しました!

**Comment by sue445** [comment]
僕は下記のいずれかでいく予定です。（両方とも [福岡Ruby会議02](http://regional.rubykaigi.org/fukuoka02/) に出したCFPなので、落ちた方をこっちで話す予定です 😅 ）

# Rubyで作るソーシャルゲームのインフラと運用
ドリコムでは多くのソーシャルゲームやwebサービスを運用し、Chefでサーバをプロビジョニングしていた。

しかし一昨年くらいからChefのレシピを全てitamaeで書き直した。
同時にソーシャルゲームの急激なアクセス数と負荷に柔軟に対応するためにインフラ構成と運用も刷新した。

今回はドリコムの新時代を切り拓くインフラを紹介したいと思う。

# OSS雑メンテ
世界にはgemが数多くリリースされている。
誰にでも簡単に作れるgemだが、メンテし続けていくのは意外に大変である。

私は社内外で多くのgemを開発していて、rubygems.orgにあるものだけでも30個を超える。
しかしリリースしている数に対してそれほど苦労はしていない。

これまでに数多くのgemを開発してメンテし続けた、雑にメンテし続けるための知見を紹介しようと思う。

**Comment by sue445** [comment]
> OSS雑メンテ

こっちでいきたいと思います。

**Comment by onk** [comment]
たぶんシリアライズ層的な話になると思います。
https://blog.onk.ninja/2017/09/21/schema_first_development の延長で。

**Comment by yhirano55** [comment]
ご登壇者各位:

登壇テーマ入稿期限の締め切りが近づいてまいりましたのでリマインドです。
期限は11/3（金）までとなりますので、期日までにタイトルと説明文をFIXいただけますと幸いです。

どうぞよろしくお願いいたします。

@willnet @joker1007 @kenchan @ppworks @JunichiIto @masuidrive @gfx @k0kubun @itkrt2y @onk @koic @sinsoku @toshimaru @yuemori @mikaji @morizyun @yasaichi @hatappi @ne-sachirou @sue445

（なお、既にFIXされている方にも念のため、お伝えしております）

**Comment by ppworks** [comment]
## タイトル

作らない技術

## 説明文（80〜200文字程度）

esaとpplogなどで、作らなかった事例を紹介しながら、最小限のコストで最大限の価値を提供するコツをお話できればと思います。

**Comment by gfx** [comment]
## タイトル

マルチテナント・ウェブアプリケーションの実践

## 説明文

Kibelaはapartment gemを使ったマルチテナント・ウェブアプリケーションであり、PostgreSQLのSchemaによりチームごとにDBの名前空間を分離しています。

このようなマルチテナントを実装・運用するなかでの学び、Railsアプリケーションという文脈で紹介します。

**Comment by onk** [comment]
トーク内容変更します。
あとで紛糾する方が面白そうだ(ぉ

## タイトル

RSpec しぐさ

## 説明文

RSpec が生まれたときの状況、何が素晴らしかったのかついて話します。
今となっては「なぜ minitest ではなく RSpec が生まれたのか」が分からないと思いますが、当時は熱狂する理由があったんです。

**Comment by morizyun** [comment]
お願いします〜

## タイトル

Rancherで作るお手軽バッチ処理環境

## 説明文

RancherというDockerクラスタ管理ツールの紹介です。

Rancherを使うとdocker-composeを入れるだけで、簡単にWebサイトを立ちあることができます。また、Rancher & Dockerを使ったバッチ処理環境が実際に便利だったのでその辺りを紹介します。

**Comment by yasaichi** [comment]
よろしくお願いします〜 :bow:

## タイトル

とある企業のモバイル対応

## 説明文

ピクスタでは今、[PIXTA](https://pixta.jp)のモバイル対応を進めています。もうすぐ2018年になるというのになぜ今（更）モバイル対応をしているのでしょうか。本発表では、モバイル対応が必要になった背景と、Ruby on Railsでの実装方法のひとつであるActionPack Variantsの概要、および段階的なリリースを行う上での問題点とその解決策をお話します。

**Comment by mikaji** [comment]
よろしくお願いします

## タイトル
Railsを学び、現場に入るまで

## 説明文
現在、Railsをイチから学ぶためにはRailsチュートリアルをこなしたり書籍などを利用すると思われる。しかし実際に現場で開発すると、アプリケーションのレイヤー構成やRailsの罠に戸惑うことがある。本発表ではRails初学者が現場で開発をするときに感じるであろうギャップをいくつか紹介する。Rails初学者、またメンターなどを行っている開発者にとって知見となることを期待する。

**Comment by koic** [comment]
## タイトル

Enter the OSS world [RuboCop] II. lost boundary

## 説明文

[福岡Ruby会議02 前夜祭](https://fukuokarb.connpass.com/event/68497/)で発表予定の『Enter the OSS world [RuboCop] I. presage comment』の続編。ソーシャルコーディングを通じて実装と設計への知識や筋を磨いて行く話です。OSS に送った Pull Request がどのよう改善され、ユーザーがもちいる形になっていくかの一過程を実例を元に話します。

**Comment by JunichiIto** [comment]
当日までにうまく内容をまとめられるか不安ですが、とりあえずこんな感じでお願いします。

## タイトル

Rails ❤️ SQL

## 説明文

前職、前々職はSQLをバリバリ使う現場で働いていました。そして現在はRailsの開発がメインです。
RailsのActiveRecordってとっても便利！ActiveRecord大好き！！・・・な僕ですが、ActiveRecordのクエリ機能だけではどうにもならないケースもあります。
そんなときこそSQL！
複雑な検索機能や集計処理を実装したり、さくっと大量のデータを一括更新したりするときにはSQLが大活躍！！
そんなわけで、この講演ではRailsにおけるSQLの使いどころや、実践的な活用テクニックを紹介します。

**Comment by 284km** [comment]
ご登壇者各位:

登壇テーマ入稿にご協力頂きありがとうございます。

入稿期限の締め切りが近づいてまいりましたのでリマインドです。
（WIP で頂いている方も含めてお伝えしております）

期限は11/3（金）までとなりますので、期日までにタイトルと説明文をFIXいただけますと幸いです。

どうぞよろしくお願いいたします。

@willnet @joker1007 @kenchan @masuidrive @itkrt2y @sinsoku @hatappi @ne-sachirou

**Comment by joker1007** [comment]
今、候補が3つあって、悩んでいる。

## 候補1
### タイトル
Railsからの脱出 ~ データストアの迷宮~

### 説明文
不用意にRailsを使ってRDBにデータをストアした大量のレコードを、Railsから引き剥がすための流れ。
そして、Railsの何がデータバウンドな処理と噛み合わないのか、それをRailsの中で回避するための工夫について。

これはなんか微妙に JunichIto さん & willnet さんとネタが被りそうだなー。

---

## 候補2
###
Professional Rails on ECS

### 説明分
かなり早期の段階でAmazon ECSを採用し、本番で運用してきた実績を元に、Railsをコンテナで運用する知見について話し、コンテナであることの利点と運用時に必要な工夫を伝えます。
また、開発環境の作り方から、イメージのビルド、デプロイを自動化する際に取った手法やツールの紹介をします、

---

## 候補3
### タイトル
Pragmatic Rails DDD Tactics

### 説明文
イマイチ噛み合わないRailsとDDDというものについて、自分なりに考えてみた考察と、現実的な範囲でDDDの戦術パターンをRailsの中でどう表現するかについて話します。
戦略的な話しは、もっと業務のやり方全体の話になるのでしません。

---

さて、どれにするか……。

**Comment by willnet** [comment]
WIPのやつ、そのままWIPを外しました

**Comment by yhirano55** [comment]
> Pragmatic Rails DDD Tactics

聞いてみたい...!!

**Comment by sinsoku** [comment]
話す内容はまだ下記の2つで悩んでいるので、今日・明日で決めて投稿します。

1. 稀に落ちるテストと戦う方法
2. 初心者はRailsのレールを伸ばすな

willnet さんの発表の後に「レールを伸すことのデメリット、失敗する事例」を話すのも面白いだろうなーと思いつつ、稀に落ちるテストの方が参加者に有益っぽい気もするので。

**Comment by yhirano55** [comment]
> レールを伸すことのデメリット、失敗する事例

ケースバイケースなので、聞いてみたさ...!!

**Comment by kenchan** [comment]
@yhirano55 

お昼に相談させていただいた通り、2名での登壇とさせてください！概要はこんな感じで考えています！ kymmt90のプロフィールについては明日中にお送りします＞＜

## タイトル

GMOペパボの Rails & Vue.js プロダクト開発の現場

## 説明

私たちが携わっている新たなプロダクトの開発について、チームビルディングやプロジェクト運営の視点を kenchan が、Swagger(OpenAPI)を用いてサーバサイドとクライアントサイドを効率的に並行開発する方法について kymmt90 が発表します。

**Comment by itkrt2y** [comment]
ラフな趣にしてみました

## タイトル

ざっくり学ぶ言語のしくみ

## 説明文

2017年も終わりですね。
今年僕が一番勉強したのは何かを考えたら言語処理系だったので、個人的な今年の総括の意味も込めて言語処理系初心者向けにざっくりとプログラミング言語のしくみについて解説したいと思います。

**Comment by kenchan** [comment]
https://github.com/railsdm/meetup/issues/15#issuecomment-341363085 もう1名の登壇者情報です！よろしくお願いします〜

- 氏名
  - 山本浩平
- 所属・部署・肩書
  - GMOペパボ株式会社 EC事業部
- 各種URL（Twitter, GitHub）
  - https://twitter.com/kymmt90
  - https://github.com/kymmt90
- 紹介文（50〜200文字程度）
  - 2016年にGMOペパボへ入社し、Webアプリケーションエンジニアとしてのキャリアを開始。これまで、主にネットショップ作成サービス「カラーミーショップ」のバックエンドを支えるRails製Web APIの開発に従事。最近は、新プロダクトのWeb APIをOpenAPIなどを利用して効率的に開発することに興味あり。
- プロフィール画像URL or （GitHub/Twitterのを使ってね、でも可です）
  - GitHub/Twitterのを使ってね

**Comment by hatappi** [comment]
## タイトル
2018年から始めるRubyによる深層学習入門

## 説明文

2017年にRed Data ToolsというRubyのためのデータ分析を提供するOSSプロジェクトが立ち上がり私はそこで深層学習フレームワークをRubyで作ってます。
その話をRailsを交えながら紹介していきます。

**Comment by ne-sachirou** [comment]
タイトル
--
外傷的Elixir

説明文
--
高速でpararellに処理でき、落ちない分散システムを作り易いといわれる[Elixir](https://elixir-lang.org/)。Rubyに似た文法と標準ライブラリを持ち、Railsに似たWebアプリケーションフレームワーク[Phoenix](http://phoenixframework.org/)が在りと、一見Rubyistと相性が良さそうです。しかしその内実はClojureを元とした関数型言語であり、Erlang/OTPを基盤に使うアクターモデルの環境でもあり、Elixirでシステムを作ってゆく(Alchemistになる)には不変なデータを使ったプログラミングとプロセス設計の技能が必要です。
今回はRubyistだらけのチームがAlchemistのチームになっていった過程を振り返りつつ、Elixirの魅力を紹介します。

- - -

よろしくお願いいたします。

**Comment by masuidrive** [comment]
面白いのでタイトル被せて見ることにしましたｗ

## タイトル
Rails ❤️ React

## 説明文
Rails 5.1では`webpacker gem`によってReactやAngularといったJavascriptのフロントエンドフレームワークが直接サポートされるようになりました。
これを利用しReactを使ったviewの作りかたやPros & Consを解説します。

**Comment by sinsoku** [comment]
「初心者はRailsのレールを伸ばすな」はLTにするには微妙そうだったので、テストの話にします。

## タイトル

Randomly Failing Specs

## 説明文

Rails でテストコードを書き、CI で継続的にテストを実行するのは既に一般的だと思います。
しかし、テストコードが増えてくると「稀に落ちるテスト」というものが現れ始めます。

そんな稀に落ちるテストの原因、戦い方をいくつか紹介したいと思います。

**Comment by yuemori** [comment]
slackでAPIサーバのテストの話をするっていう話でしたが、業務でがっつり触ってるDockerの方が熱い話ができそうだったので、そっちの話にします！

## タイトル

Rails 🆚  Docker

## 説明文

Docker使ってますか？
Rails on Dockerの事例は増えつつありますが、導入方法や構成について語られることが多く、苦しみやすい・難しい点について語られることはあまりないように思います。
今回はRuby/RailsでDockerを使ってきて戦った点とその解決方法について話します。

**Comment by joker1007** [comment]
一旦、これで確定します。

## 候補2
###
Professional Rails on ECS

### 説明分
かなり早期の段階でAmazon ECSを採用し、本番で運用してきた実績を元に、Railsをコンテナで運用する知見について話し、コンテナであることの利点と運用時に必要な工夫を伝えます。
また、開発環境の作り方から、イメージのビルド、デプロイを自動化する際に取った手法やツールの紹介をします、

---

話が被らなそうで具体的な話ができるので。
他のトピックについては、またどっかで機会があれば話します。

**Comment by joker1007** [comment]
と思ったら、すぐ上で被ってんなw
まあいいかw

**Comment by yhirano55** [comment]
みなさまご対応ありがとうございました。事前に連絡しておりますとおり、当日は、大阪会場にも中継いたしますため、Google Hangoutに接続していただき、ご登壇いただきます。

連絡: 当日はMeetup終了後の19:30より、別会場にて懇親会をセッティングしました。登壇者21名の参加費は無料で、申込みも不要です。

https://techplay.jp/event/636561

登壇テーマの入稿にご協力いただき、本当にありがとうございました。

**Comment by yhirano55** [comment]
# 懇親会に関するお願い

↑で **申込み不要** と記載していましたが、当日の全体の参加状況を把握したいため、お気付きになられましたら、申込み手続きをお願いいたします（ご登壇者用の無料参加枠があります）

https://techplay.jp/event/636561

お手数ですがよろしくお願いいたします:bow:
