### ISSUE TITLE
Rails Developers Meetup 2017: プロフィール 入稿窓口

### ISSUE THREAD

**Issue by yhirano55** [railsdm/meetup#16]
この度は、『Rails Developers Meetup 2017』のご登壇をお引き受けいただき、
誠にありがとうございます。

募集ページに登壇テーマを掲載するため、ご協力のほどお願いいたします。

### 募集ページ

https://techplay.jp/event/631431
閲覧用パスワード: HoqUO4I1

### フォーマット

1. 氏名
2. 所属・部署・肩書
3. 各種URL（Twitter, GitHub）
4. 紹介文（50〜200文字程度）
5. プロフィール画像URL or （GitHub/Twitterのを使ってね、でも可です）

### 入稿方法

こちらのIssueのコメントフォームよりご投稿ください。
確認でき次第、募集ページを更新します。

### スケジュール

- 入稿期限: 2017/9/29（金）
- 募集開始: 2017/10/2（月）12:00から

**Comment by hatappi** [comment]
## 1. 氏名
畑中 悠作 (はたなか ゆうさく)

## 所属・部署・肩書
所属：株式会社Speee
部署：デジタルコンサルティング事業本部 アドテク事業部 UZOU事業
肩書： UZOU事業エンジニア

## 各種URL
- Twitter: https://twitter.com/hatappi
- Github: https://github.com/hatappi

## 紹介文
株式会社Speee エンジニア。新卒として2014年に入社し社内システムの開発を行った後現在はネイティブアド配信プラットフォームのUZOUで開発を行っている。最近はRuby用のデータ処理ツールを提供するためのプロジェクト「Red Data Tools」の開発も個人的に参加している。

## プロフィール画像URL
Twitterの画像でお願いします。
https://pbs.twimg.com/profile_images/896275871941574656/wAcSCGy4_400x400.jpg

**Comment by toshimaru** [comment]
## 氏名

榎本　敏丸 (えのもと　としまる)

## 所属・部署・肩書

所属：株式会社Gunosy
部署：開発本部 広告技術部
肩書： エンジニア

## 各種URL

- Twitter: https://twitter.com/toshimaru_e
- GitHub: https://github.com/toshimaru

## 紹介文

エンジニア＠株式会社Gunosy。Roppongi.rbオーガナイザー。社内のRailsプロダクトを全般的に見ている。最近はGoやPythonも書く。

## プロフィール画像URL

GitHub のでお願いします。

**Comment by yasaichi** [comment]
## 氏名
後藤 優一（ごとう ゆういち）

## 所属・部署・肩書
所属: ピクスタ株式会社
部署: 開発部 技術推進チーム
肩書: リーダー

## 各種URL
- Twitter: https://twitter.com/_yasaichi
- Github: https://github.com/yasaichi

## 紹介文
2015年に新卒入社後、開発効率の改善や開発基盤の整備を担当。2016年12月から開発部技術推進チームのリーダーに就任。開発プロセスの改善や開発基盤の整備を先導する傍ら、大規模プロジェクトにおける技術支援も行っている。

## プロフィール画像URL
Twitterの画像でお願いします〜
https://pbs.twimg.com/profile_images/540905653418471427/JysydFaP_400x400.png

**Comment by morizyun** [comment]
## 氏名

森　賢児(もり　けんじ)

## 所属・部署・肩書

所属：M3
部署：エンジニアリンググループ
肩書：エンジニア

## 各種URL

Twitter: https://twitter.com/zyunnosuke
Github: https://github.com/morizyun
紹介文

「酒と泪とRubyとRails」というブログを書いています。最近はDBのindexをひたすら貼り続けています。あと、React.js + Reduxのアプリ開発や、Rancher + Dockerで四苦八苦しています！

## プロフィール画像URL

Twitterの画像でお願いします。
https://pbs.twimg.com/profile_images/699186609585934337/mWjyFW5T_400x400.png

**Comment by mikaji** [comment]
## 氏名

三上 光司(みかみ　こうじ)

## 所属・部署・肩書

所属：株式会社リクルートマーケティングパートナーズ
部署：ネットビジネス本部 プロダクトディベロップメント部 kidsly開発Ｇ
肩書：エンジニア

## 各種URL

Twitter: https://twitter.com/mikaji_jp
Github: https://github.com/mikaji

## 紹介文

2017年（今年）リクルートに新卒入社。社内で数少ないRailsアプリケーションのひとつである保育園向けサービス kidsly の開発に携わる。Rails歴は2年ほど。最近はPycallに興味がある。

## プロフィール画像URL

Twitterの画像でお願いします。
https://pbs.twimg.com/profile_images/861265627150929920/_QUwt_fc_400x400.jpg

**Comment by itkrt2y** [comment]
## 氏名

板倉 達也（いたくら たつや）

## 所属・部署・肩書

所属：タケユー・ウェブ株式会社  
肩書き：エンジニア

## 各種URL（Twitter, GitHub）

Twitter: http://twitter.com/itkrt2y  
GitHub: https://github.com/itkrt2y

## 紹介文

Ruby歴3年ほどの気ままなジョブホッパー。最近はタケユー・ウェブ株式会社というRailsメインの受託会社でReact SPA on RailsをただのRailsに戻したり、新規スマホアプリ開発をやったりしています。

## プロフィール画像URL

Twitterのでお願いします
https://pbs.twimg.com/profile_images/523402090320625664/V0UxQkVx_400x400.jpeg

**Comment by kenchan** [comment]
## 氏名

髙橋健一 (たかはし けんいち)

## 所属・部署・肩書

所属: GMOペパボ株式会社
部署: EC事業部
肩書: チーフテクニカルリード

## 各種URL

Twitter: https://twitter.com/kenchan
GitHub: https://github.com/kenchan

## 紹介文

2014年にGMOペパボ株式会社へ入社、技術基盤チームの一員として様々なサービスの技術支援に従事。2016年よりEC事業部のCTLに就任し、サービス開発や開発運用基盤の整備、技術者組織作りに取り組んでいる。

プロフィール画像URL

Twitter、facebook、GitHub全部同じ画像なのでどれでもOKです！

**Comment by ne-sachirou** [comment]
氏名
--
井上 幸亨郎 (いのうえ さちろう)

所属・部署・肩書
--
所属 : 株式会社ドリコム
部署 : ゲームデベロップメント1部
肩書 : サーバーサイドエンジニア

各種URL
--
プロフィール : http://c4se.jp/profile/ne_sachirou

紹介文
--
言語濫用者。やり過ぎた言語が好きです。最近はElixir/Phoenixでゲームのロジックを書いたり、Haskellを愛好したりしています。

プロフィール画像URL
--
[さっちゃん, Tokyo Japan - Gravatar プロフィール](https://ja.gravatar.com/nesachirou)
