### ISSUE TITLE
railsdm 2017 懇親会会場を決める

### ISSUE THREAD

**Issue by 284km** [railsdm/meetup#18]
* [Rails Developers Meetup 2017｜IT勉強会・セミナーなどのイベント情報検索サービス - TECH PLAY［テックプレイ］](https://techplay.jp/event/631431)

定員 170 名の会の懇親会会場を決める。渋谷近辺。

**Comment by 284km** [comment]
あまり決まりごとは無いけれど、だいたいこういう方向で進めている

- なるべく一箇所の店に全員入りたい。どうしても無理そうな時に分散という手段。きっと入る。
- 全員席があるより、スタンディング（席もあってよいけど）の方が色々とよさそう

**Comment by 284km** [comment]
現状候補
- 串カツ田中
- 北海道

next action: ざっくり試算して串カツ田中に問い合わせる

**Comment by yhirano55** [comment]
下記に決まったのでクローズ
http://xn---jack-kq4da7x0kx030aho4cixydymb.com/
