### ISSUE TITLE
Rails Developers Podcast #1

### ISSUE THREAD

**Issue by yhirano55** [railsdm/meetup#23]
## Tasks

- [ ] Create show notes
- [ ] Assign guest
- [ ] Assign schedule

💪

**Comment by yhirano55** [comment]
とりあえず収録してみる。公開する方法等は、収録後に調べる。

**Comment by 284km** [comment]
🎙  爆誕〜

**Comment by yhirano55** [comment]
いきなりこっちに移動のためクローズ
https://github.com/railsdp/rec/issues/1
